version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: edtech-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: edtech
      MYSQL_USER: edtechuser
      MYSQL_PASSWORD: edteachuser123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: edtech-backend
    depends_on:
      - mysql
    volumes:
      - ./backend:/var/www/html
    expose:
      - "8000"
    command: ["/usr/local/bin/start.sh"]
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: edtech
      DB_USERNAME: edtechuser
      DB_PASSWORD: edteachuser123

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: edtech-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    expose:
      - "3000"
    command: ["sh", "-lc", "tr -d '\\r' < ./start.sh > /tmp/start && sh /tmp/start"]

  nginx:
    image: nginx:alpine
    container_name: edtech-nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
